# Set the build language
language: python

# Set the python version
python: 3.7

# Install the dependencies
install:
  - pip install -r requirements.txt

# Run formatting and unit tests
script:
  - black pesis
  - coverage run -m pytest

# Push the results back to codecov
after_success:
  - codecov
